"""Add contribution and activity tables

Revision ID: 1b49d768632e
Revises: 
Create Date: 2025-11-07 13:36:04.891781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b49d768632e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_external_id'), 'activities', ['external_id'], unique=True)
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_table('contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contributions_external_id'), 'contributions', ['external_id'], unique=True)
    op.create_index(op.f('ix_contributions_id'), 'contributions', ['id'], unique=False)
    op.create_table('project_member_association',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('project_stack_association',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('stack_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['stack_id'], ['stacks.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'stack_id')
    )
    op.execute("UPDATE invitations SET role = CASE WHEN role IN ('developer', 'consultant', 'admin') THEN 'intern' ELSE role END")
    op.execute("CREATE TYPE userrole AS ENUM ('intern', 'mentor', 'organization')")
    op.alter_column('invitations', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('intern', 'mentor', 'organization', name='userrole', native_enum=True),
               existing_nullable=False,
               postgresql_using="role::userrole")
    op.drop_constraint(op.f('invitations_email_key'), 'invitations', type_='unique')
    op.drop_constraint(op.f('invitations_invitation_code_key'), 'invitations', type_='unique')
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=True)
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.create_index(op.f('ix_invitations_invitation_code'), 'invitations', ['invitation_code'], unique=True)
    op.drop_constraint(op.f('invitations_organization_id_fkey'), 'invitations', type_='foreignkey')
    op.create_foreign_key(None, 'invitations', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'project_members', 'projects', ['project_id'], ['id'])
    op.alter_column('projects', 'stacks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('projects', 'linked_documents',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('projects', 'pm_integration_method',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('OAUTH2', 'API_KEY', 'WEBHOOK', name='integrationmethod'),
               existing_nullable=True)
    op.alter_column('projects', 'vc_integration_method',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('OAUTH2', 'API_KEY', 'WEBHOOK', name='integrationmethod'),
               existing_nullable=True)
    op.alter_column('projects', 'comm_integration_method',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('OAUTH2', 'API_KEY', 'WEBHOOK', name='integrationmethod'),
               existing_nullable=True)
    op.alter_column('projects', 'comm_notifications',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('projects', 'createdAt',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_constraint(op.f('stacks_name_key'), 'stacks', type_='unique')
    op.create_index(op.f('ix_stacks_id'), 'stacks', ['id'], unique=False)
    op.create_index(op.f('ix_stacks_name'), 'stacks', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stacks_name'), table_name='stacks')
    op.drop_index(op.f('ix_stacks_id'), table_name='stacks')
    op.create_unique_constraint(op.f('stacks_name_key'), 'stacks', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.alter_column('projects', 'updatedAt',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('projects', 'createdAt',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'comm_notifications',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('projects', 'comm_integration_method',
               existing_type=sa.Enum('OAUTH2', 'API_KEY', 'WEBHOOK', name='integrationmethod'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('projects', 'vc_integration_method',
               existing_type=sa.Enum('OAUTH2', 'API_KEY', 'WEBHOOK', name='integrationmethod'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('projects', 'pm_integration_method',
               existing_type=sa.Enum('OAUTH2', 'API_KEY', 'WEBHOOK', name='integrationmethod'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('projects', 'linked_documents',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('projects', 'stacks',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.create_foreign_key(op.f('invitations_organization_id_fkey'), 'invitations', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_invitations_invitation_code'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.create_unique_constraint(op.f('invitations_invitation_code_key'), 'invitations', ['invitation_code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('invitations_email_key'), 'invitations', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('invitations', 'role',
               existing_type=sa.Enum('intern', 'mentor', 'organization', 'developer', name='userrole', native_enum=True),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.execute("DROP TYPE userrole")
    op.drop_table('project_stack_association')
    op.drop_table('project_member_association')
    op.drop_index(op.f('ix_contributions_id'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_external_id'), table_name='contributions')
    op.drop_table('contributions')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_external_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
